/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recettes;

import java.util.List;
import java.util.Optional;

public class App {

    private static final String recettesPath = "app/src/main/resources/recettes.json";
    private static final String outputPath = "app/src/main/resources/listeAchat.txt";

    public static void main(String[] args) {
        Lecteur lecteur = new Lecteur(recettesPath);
        Ecriveur ecriveur = new Ecriveur(outputPath);
        Parser parser = new JsonParser();
        List<Optional<List<Recette>>> recettes = parser.parse(lecteur);
        Selecteur selecteur = new Selecteur(recettes);

        Optional<List<Recette>> choix = selecteur.faireChoix();
        if (choix.isPresent()) {
            List<Recette> aff = choix.get();
            StringBuffer collage = new StringBuffer();
            aff.stream()
                    .filter((recette) -> recette != null)
                    .forEach((recette) -> {
                        collage.append(recette.toString());
                    });
            ecriveur.ecrire(collage.toString());
        } else {
            System.out.println("Impossible de générer un choix. Ajoutez des possibilités!");
        }

    }
}
