/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recettes;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public class App {

    private static final String recettesPath = "app/src/main/resources/recettes.json";
    private static final String outputPath = "app/src/main/resources/listeAchat.txt";

    public static void main(String[] args) {
        Lecteur lecteur = new Lecteur(recettesPath);
        Ecriveur ecriveur = new Ecriveur(outputPath);
        Map<String, List<Recette>> recettes = new JsonParser().parse(lecteur);
        Map<String, Optional<Recette>> choix = new Selecteur(recettes).faireChoix();

        ecriveur.ecrire(genererAffichage(choix));

    }

    public static String genererAffichage(Map<String, Optional<Recette>> choix) {
        StringBuffer header = new StringBuffer();
        StringBuffer body = new StringBuffer();
        Map<String, Ingredient> combinaison = new HashMap<>();
        choix.forEach((temps, recette) -> {
            if (recette.isPresent()) {
                Recette rec = recette.get();
                header.append("\n" + temps + " : " + rec.toString());
                combinaison.putAll(rec.combinerIngredients(combinaison));

            }
        });
        header.append("\n\n");
        combinaison.forEach(
                (nom, ingredient) -> body
                        .append("\n" + ingredient.nom + ", " + ingredient.volume + "; " + ingredient.poid));

        return header.toString() + body.toString();
    }

}
